pretrained_model_path: "./ckpt/stable-diffusion-v1-5"

logdir: "./runs"
validation_sample_logger:
    num_inference_steps: 40
    guidance_scale: 7
train_steps: 2000
validation_steps: 100
checkpointing_steps: 500
seed: 6666
mixed_precision: 'fp16'
learning_rate: 1e-5